perp-javascript-objects - Brighitte Johnson
brij8/prep-91621-code-solutions pull request #11
Opened 2021-09-28 01:15 UTC by brij8

![prep-javascript-objects](https://user-images.githubusercontent.com/42279790/135006236-080d6935-93e8-42c3-a446-2e804c210b83.png)

2021-09-29 14:26 UTC, thebearingedge requested changes

2021-09-29 14:26 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +var fullName = 'Crash' + ' Override';
Hi Brighitte, you can access the first and last names of the person using dot notation. Also, sick reference 😆 

```js
var fullName = person.firstName + ' ' + person.lastName;
```

2021-09-29 19:17 UTC, brij8 commented on prep-javascript-objects/main.js
> +var fullName = 'Crash' + ' Override';
haha thx ;D
so yeh, I left the wrong line commented out. Line 7 is some string cheese, but line 8 has the correct dot notation concatenation. Swapped it.

![prep-javascript-objects_fix](https://user-images.githubusercontent.com/42279790/135334047-c4d63c5a-7d71-4144-8708-668a7cc84f86.png)

2021-09-30 00:59 UTC, thebearingedge approved these changes

2021-09-30 01:56 UTC, merged